# Generated by Django 2.0.2 on 2018-04-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RemoveField(
            model_name='Profile',
            name='username',
        )
    ]
