# Generated by Django 2.0.2 on 2018-02-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default='38c967fa', editable=False, primary_key=True, serialize=False)),
                ('date_joined', models.DateField(verbose_name='date_joined')),
                ('username', models.CharField(max_length=50)),
                ('happiness', models.IntegerField(default=0, verbose_name='e_happiness')),
                ('sadness', models.IntegerField(default=0, verbose_name='e_sadness')),
                ('disgust', models.IntegerField(default=0, verbose_name='e_disgust')),
                ('anger', models.IntegerField(default=0, verbose_name='e_anger')),
                ('surprise', models.IntegerField(default=0, verbose_name='e_surprise')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default='f4464668', editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(help_text='Insert video title here', max_length=100)),
                ('video_link', models.TextField(help_text='Insert video link here', max_length=1000, verbose_name='video_link')),
                ('happiness', models.IntegerField(default=0, verbose_name='e_happiness')),
                ('sadness', models.IntegerField(default=0, verbose_name='e_sadness')),
                ('disgust', models.IntegerField(default=0, verbose_name='e_disgust')),
                ('anger', models.IntegerField(default=0, verbose_name='e_anger')),
                ('surprise', models.IntegerField(default=0, verbose_name='e_surprise')),
                ('date_shared', models.DateField()),
                ('total_views', models.IntegerField(default=0, verbose_name='total_views')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reelfeels.User')),
            ],
            options={
                'ordering': ['-date_shared'],
            },
        ),
        migrations.CreateModel(
            name='VideoToUser',
            fields=[
                ('id', models.UUIDField(default='c293fa3c', editable=False, primary_key=True, serialize=False)),
                ('happiness', models.IntegerField(default=0, verbose_name='e_happiness')),
                ('sadness', models.IntegerField(default=0, verbose_name='e_sadness')),
                ('disgust', models.IntegerField(default=0, verbose_name='e_disgust')),
                ('anger', models.IntegerField(default=0, verbose_name='e_anger')),
                ('surprise', models.IntegerField(default=0, verbose_name='e_surprise')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reelfeels.User')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reelfeels.Video')),
            ],
        ),
    ]
