# Generated by Django 2.0.2 on 2018-04-26 21:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Write your comment here!', max_length=1000, verbose_name='The text content of a comment')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/')),
                ('happiness', models.IntegerField(default=0, verbose_name='Overall happiness')),
                ('sadness', models.IntegerField(default=0, verbose_name='Overall sadness')),
                ('disgust', models.IntegerField(default=0, verbose_name='Overall disgust')),
                ('anger', models.IntegerField(default=0, verbose_name='Overall anger')),
                ('surprise', models.IntegerField(default=0, verbose_name='Overall surprise')),
                ('last_updated_emotions', models.DateField(blank=True, null=True, verbose_name='When overall emotions were last calculated')),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(default='An Emotional Video!', help_text='Insert video title here', max_length=100, verbose_name='Title')),
                ('video_link', models.TextField(help_text='Insert video link here', max_length=1000, verbose_name='Link to Video')),
                ('video_description', models.TextField(default='Am I happy? Sad? Disgusting?? Watch me to find out!', max_length=1000, verbose_name='Video Description')),
                ('happiness', models.IntegerField(default=0, verbose_name='Global happiness')),
                ('sadness', models.IntegerField(default=0, verbose_name='Global sadness')),
                ('disgust', models.IntegerField(default=0, verbose_name='Global disgust')),
                ('anger', models.IntegerField(default=0, verbose_name='Global anger')),
                ('surprise', models.IntegerField(default=0, verbose_name='Global surprise')),
                ('last_updated_emotions', models.DateField(default=datetime.date.today, null=True)),
                ('yesterdays_views', models.IntegerField(default=0, verbose_name='Yesterdays views')),
                ('todays_views', models.IntegerField(default=0, verbose_name='Todays views')),
                ('date_shared', models.DateField()),
                ('uploader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reelfeels.Profile')),
            ],
            options={
                'ordering': ['-date_shared'],
                'permissions': (('can_edit', 'Can edit video'),),
            },
        ),
        migrations.CreateModel(
            name='ViewInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_watched', models.DateField(verbose_name='Date updated')),
                ('happiness', models.IntegerField(default=0, verbose_name='Happiness')),
                ('sadness', models.IntegerField(default=0, verbose_name='Sadness')),
                ('disgust', models.IntegerField(default=0, verbose_name='Disgust')),
                ('anger', models.IntegerField(default=0, verbose_name='Anger')),
                ('surprise', models.IntegerField(default=0, verbose_name='Surprise')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reelfeels.Video')),
                ('viewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reelfeels.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reelfeels.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reelfeels.Video'),
        ),
    ]
