# Generated by Django 2.0.2 on 2018-02-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelfeels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='b158e8a9', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default='f3a3f906', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videotouser',
            name='id',
            field=models.UUIDField(default='d50c50de', editable=False, primary_key=True, serialize=False),
        ),
    ]
