# Generated by Django 2.0.2 on 2018-04-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelfeels', '0002_auto_20180426_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewinstance',
            name='calculated_anger',
            field=models.IntegerField(default=0, verbose_name='Calculated Anger'),
        ),
        migrations.AlterField(
            model_name='viewinstance',
            name='calculated_disgust',
            field=models.IntegerField(default=0, verbose_name='Calculated Disgust'),
        ),
        migrations.AlterField(
            model_name='viewinstance',
            name='calculated_happiness',
            field=models.IntegerField(default=0, verbose_name='Calculated Happiness'),
        ),
        migrations.AlterField(
            model_name='viewinstance',
            name='calculated_sadness',
            field=models.IntegerField(default=0, verbose_name='Calculated Sadness'),
        ),
        migrations.AlterField(
            model_name='viewinstance',
            name='calculated_surprise',
            field=models.IntegerField(default=0, verbose_name='Calculated Surprise'),
        ),
    ]
