# Generated by Django 2.0.2 on 2018-04-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelfeels', '0003_auto_20180426_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewinstance',
            name='previous_anger',
            field=models.IntegerField(default=0, verbose_name='Anger'),
        ),
        migrations.AddField(
            model_name='viewinstance',
            name='previous_disgust',
            field=models.IntegerField(default=0, verbose_name='Disgust'),
        ),
        migrations.AddField(
            model_name='viewinstance',
            name='previous_happiness',
            field=models.IntegerField(default=0, verbose_name='Happiness'),
        ),
        migrations.AddField(
            model_name='viewinstance',
            name='previous_sadness',
            field=models.IntegerField(default=0, verbose_name='Sadness'),
        ),
        migrations.AddField(
            model_name='viewinstance',
            name='previous_surprise',
            field=models.IntegerField(default=0, verbose_name='Surprise'),
        ),
    ]
