# Generated by Django 2.0.2 on 2018-02-24 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reelfeels', '0003_auto_20180224_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videotouser',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date_updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='a22472df', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(default='bfd51f87', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videotouser',
            name='id',
            field=models.CharField(default='8e7feb0b', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
