# Generated by Django 2.0.2 on 2018-02-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reelfeels', '0005_auto_20180224_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default='fd6e122d', editable=False, max_length=8, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Write your comment here!', max_length=1000, verbose_name='The text content of a comment')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='video_description',
            field=models.TextField(max_length=1000, null=True, verbose_name='Video Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='anger',
            field=models.IntegerField(default=0, verbose_name='Overall anger'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disgust',
            field=models.IntegerField(default=0, verbose_name='Overall disgust'),
        ),
        migrations.AlterField(
            model_name='user',
            name='happiness',
            field=models.IntegerField(default=0, verbose_name='Overall happiness'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='afdb32f3', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='sadness',
            field=models.IntegerField(default=0, verbose_name='Overall sadness'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surprise',
            field=models.IntegerField(default=0, verbose_name='Overall surprise'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(default='e2c01cf4', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.TextField(help_text='Insert video title here', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.TextField(help_text='Insert video link here', max_length=1000, verbose_name='Link to Video'),
        ),
        migrations.AlterField(
            model_name='videotouser',
            name='id',
            field=models.CharField(default='a68b4f47', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reelfeels.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reelfeels.Video'),
        ),
    ]
