# Generated by Django 2.0.2 on 2018-02-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelfeels', '0006_auto_20180227_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='49250d43', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='21e04a50', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='anger',
            field=models.IntegerField(default=0, verbose_name='Global anger'),
        ),
        migrations.AlterField(
            model_name='video',
            name='disgust',
            field=models.IntegerField(default=0, verbose_name='Global disgust'),
        ),
        migrations.AlterField(
            model_name='video',
            name='happiness',
            field=models.IntegerField(default=0, verbose_name='Global happiness'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(default='2116540f', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='sadness',
            field=models.IntegerField(default=0, verbose_name='Global sadness'),
        ),
        migrations.AlterField(
            model_name='video',
            name='surprise',
            field=models.IntegerField(default=0, verbose_name='Global surprise'),
        ),
        migrations.AlterField(
            model_name='video',
            name='total_views',
            field=models.IntegerField(default=0, verbose_name='Total views'),
        ),
        migrations.AlterField(
            model_name='videotouser',
            name='anger',
            field=models.IntegerField(default=0, verbose_name='Anger'),
        ),
        migrations.AlterField(
            model_name='videotouser',
            name='date_updated',
            field=models.DateField(verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='videotouser',
            name='disgust',
            field=models.IntegerField(default=0, verbose_name='Disgust'),
        ),
        migrations.AlterField(
            model_name='videotouser',
            name='happiness',
            field=models.IntegerField(default=0, verbose_name='Happiness'),
        ),
        migrations.AlterField(
            model_name='videotouser',
            name='id',
            field=models.CharField(default='93533a89', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videotouser',
            name='sadness',
            field=models.IntegerField(default=0, verbose_name='Sadness'),
        ),
        migrations.AlterField(
            model_name='videotouser',
            name='surprise',
            field=models.IntegerField(default=0, verbose_name='Surprise'),
        ),
    ]
