# Generated by Django 2.0.2 on 2018-02-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelfeels', '0007_auto_20180227_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='50237611', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='ffb7ce92', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(default='c0da9733', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videotouser',
            name='id',
            field=models.CharField(default='0ee44e2d', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
